### ISSUE TITLE
ワトソンのキーワード判別

### ISSUE THREAD

**Issue by sieben-leon** [konnyaku256/akatsuki_pants#7]
https://github.com/watson-developer-cloud/unity-sdk/blob/32d8abd987a11ae5240de572cd83af9deb98f978/Scripts/Services/SpeechToText/V1/SpeechToTextServiceExtension.cs#L188
このプロパティにkeyword入れておけば、判定しれくれそう、精度はわからない

**Comment by sieben-leon** [comment]
@konnyaku256

**Comment by konnyaku256** [comment]
調べていただいてありがとうございます！
試してみます！

**Comment by konnyaku256** [comment]
#9 で実装してみました
認識精度はそれなりに改善していそうです
